name: attendence_system_dashboard
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  two_dimensional_scrollables: 0.1.0
  cupertino_icons: ^1.0.8
  http: ^0.13.5
  intl: ^0.18.1
  get_storage:
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:

  uses-material-design: true